### ISSUE TITLE
CB02507 [厂@(邱-丘+墨)]

### ISSUE THREAD

**Issue by CallMeNP** [cbeta-org/cbeta_gaiji#1]
CB02507 的 norm_uni_char 應爲 [U+2B46E ](https://zi.tools/zi/%F0%AB%91%AE)
區別就是 `厂` 的筆畫橫，是否包住`阝`。

例：「子有事緣往[厂@(邱-丘+墨)]肆，  暫時貨易未還家，」《大乘本生心地觀經》卷4(T03n0159_p0308c24)

檢查高麗藏再雕、宮內廳福州藏，的此卷經文，均爲：U+2B46E。

另一個方案是 [U+22305 ](https://zi.tools/zi/%F0%A2%8C%85)，就是`厂`改为`广`，含義一樣。今按高麗藏推薦前字。

**Comment by CallMeNP** [comment]
高麗藏沒有在線圖片，宮內廳福州藏見： https://db2.sido.keio.ac.jp/kanseki/T_bib_frame.php?id=007075-5814&page=12#

**Comment by mahawu** [comment]
這按我們的處理模式是將 [U+2B46E](https://zi.tools/zi/%F0%AB%91%AE) 設為 CB02507 的 uni 通用字——這請 heaven 加入缺字資料庫。
