### ISSUE TITLE
CB02675 [楑-天+示]

### ISSUE THREAD

**Issue by CallMeNP** [cbeta-org/cbeta_gaiji#2]
組字式所表達的漢字爲 https://zi.tools/zi/%E2%BF%B0%E6%9C%A8%F0%A5%99%8A ，unicode未收錄。

據該網頁推薦漢字：[U+23624](https://zi.tools/zi/%F0%A3%98%A4) `𣘤`，兩字差異在右上角。

----

注意到：U+23624 `𣘤` 在Gaiji數據中記錄爲 CB02608 `[木*祭]`

CB02675 `[楑-天+示]` 僅出現一次，即：
* 「或食[楑-天+示]米」《中阿含經》卷45(T01n0026_p0712b09)。

CB02608 `[木*祭]` 出現兩次：
* 「或食𣘤米」《中阿含經》卷26(T01n0026_p0592b19 ~ T01n0026_p0592b20)。**（用這個字是對的，但標記爲CB02608則與原圖不符，應標記爲CB02675）**
*  [X72n1439_p0625c14](https://cbetaonline.dila.edu.tw/zh/X72n1439_p0625c14)

查閱大正藏原圖，上述《中阿含經》的兩處文字，原圖相同，均爲CB02675 `[楑-天+示]`。應予統一。

**Comment by mahawu** [comment]
就我所見，《中阿含經》這兩處文字，原圖不完全相同，如下：

T01n0026_p0712b09：![T01n0026_p0712b09](https://github.com/cbeta-org/cbeta_gaiji/assets/4393544/d918ec22-d001-40d9-8ba0-d5b145421715)

T01n0026_p0592b20：![T01n0026_p0592b20](https://github.com/cbeta-org/cbeta_gaiji/assets/4393544/121bb4c3-138e-429b-b9ab-b5b0dd345c93)

大正藏有初版跟修訂版，CBETA 採用修訂版（大正新修大藏經刊行會 編／東京：大藏出版株式會社，Popular Edition in 1988）為底本。

我們會將「𣘤」列為 CB02675 [楑-天+示] 的 unicode 近似字，如此未來 CB02675 [楑-天+示] 可選擇以「𣘤」來呈現。
