### ISSUE TITLE
一部分gaiji的識別（16個）

### ISSUE THREAD

**Issue by CallMeNP** [cbeta-org/cbeta_gaiji#3]
我們在集選一部分佛經進行整理，供大衆閱讀。現在將工作中遇到的所有gaiji統一整理，做個反饋。
分爲兩部分：

## 推薦爲 uni_char 即組字式表達的字
這一組推薦字大多與組字式一致。對大正藏印刷不清晰造成組字式表達有誤的，做了說明。證據不充分的也可以降級爲 通用字。

* CB02249    [((十/工)\*刀)/瓦]
  * 推薦：[㼤](https://zi.tools/zi/%E3%BC%A4)    3F24            
  * 依據：
    * 與組字式的差異在“丰”字下面是否出头。大正藏图片模糊。檢查高麗再雕原圖，共有两处，一处與推薦用字“㼤”一致。一处同组字式。
    * 字義與上下文相符
* CB02283    [宋-木+悎]
  * 推薦：[𭔋](https://zi.tools/zi/%F0%AD%94%8B)    2D50B
  * 推薦（通用字）：    悎    608E
  * 備註：通用字依據：該字僅出現在“X寤”一詞中。爲常見辭彙，應爲“悎寤”。
* CB02448    [言*害]
  * 推薦：[𬣁](https://zi.tools/zi/%F0%AC%A3%81)    2C8C1        
* CB02651    [病-丙+(白/(ㄎ*戈))]
  * 推薦：[𤻯](https://zi.tools/zi/%F0%A4%BB%AF)    24EEF
  * 依據：
    * 檢查高麗再雕原圖，與頻伽藏（即大正藏底本），可以確定下部是“成”字。是由大正藏印刷殘缺造成的困擾。
    * 此推薦字爲“瘦”字的異體字。檢查別種藏經中，有用此異體字者，也有直接寫爲“瘦”字者。
* CB02659    [菟-(色-巴)+(〦-一)]
  * 推薦：[莵](https://zi.tools/zi/%E8%8E%B5)    83B5            
* CB02737    [口*長]
  * 推薦：[𫪛](https://zi.tools/zi/%F0%AB%AA%9B)    2BA9B            
* CB04158    [噓*戈]
  * 推薦：[𡃰](https://zi.tools/zi/%F0%A1%83%B0)    210F0            
* CB04172    [莫/二/?]
  * 推薦：[謩](https://zi.tools/zi/%E8%AC%A9)    8B29            
  * 依據：
    * 東京大學網站已經識別該字爲“謩”，https://21dzk.l.u-tokyo.ac.jp/SAT2015/T1341.html
    * 大正藏鉛字較小，所以不清晰。查閱與大正藏有底本關係的幾部藏經：高麗初雕、高麗再雕、頻伽藏。均十分清晰，爲“謩”，即下面是“言”
* CB04280    [鏍-糸+廾]
  * [𰼺](https://zi.tools/zi/%F0%B0%BC%BA)    30F3A            
* CB04336    [金*(竄-臼+囚)]
  * 推薦：[𮣨](https://zi.tools/zi/%F0%AE%A3%A8)    2E8E8
  * 備註：此字應與 CB05128 合併。
  * 依據：
    * 組字式不準確，中間不能認爲是“囚”。實際應爲“𠔿”，即“囚”下面沒有橫。原圖中被誤認爲是橫的部分，其實是下面的兩個“點”。查看東京大學的高清圖可以確認這一點。
    * 該字也出現在「矛者𮣨也」《華嚴法界玄鏡》卷1(T45n1883_p0677a22)，即 CB05128。兩處原圖完全一致，已經識別爲“𮣨”。
* CB06218 [言*(卄/執/云)]
  * 推薦：[`𲂀`](https://zi.tools/zi/%F0%B2%82%80)  32080
  * 備註：
    * 此爲 Unicode Ext H 區的字。花園明朝字體中沒有收錄。
    * 此字在 cbeta_gaiji 中已經存在 norm_big_char，字形與組字式小異。本次推薦爲組字式所表達的字形。

## 推薦爲 norm_uni_char 即通用字
這一組推薦字與組字式有差異，爲異體字關係，且符合上下文。建議作爲通用字。每項列出參考依據。
* CB00700    [榳-廷+(崋-山+田)]
  * 推薦：[㮿](https://zi.tools/zi/%E3%AE%BF)    3BBF
  * 依據：
    * (汉字海)同「㮿」→㮿 bi4 (1)木名。 https://zi.tools/zi/%E2%BF%B8%F0%B0%97%93%E7%95%A2 該網頁提供了一個異體字圖譜。
    * 該字僅在T07n0220e p0945c14 出現一次。爲“X鉢羅樹”。搜索“鉢羅樹”，可以看到大量“「畢」鉢羅樹”。
* CB00819    [怡-台+(日/工)]
  * 推薦：[怛](https://zi.tools/zi/%E6%80%9B)    601B
  * 依據：
    * 該字出現的音譯詞，如“摩X理迦”爲常見詞，可以推斷該字應爲“怛”。
    * 「`[怡-台+(日/工)]`絰(上多達反下徒結反)。」《新集藏經音義隨函錄》卷3(K34n1257_p0710c12) 可以確定讀音。
    * 「怛`[怡-台+(日/工)]`(怛同並當割ㄟ)。」《紹興重雕大藏音》卷1(C059n1169_p0512a01)認爲是異體字關係。
* CB02304    [革*亢]
  * 推薦：[𩉳](https://zi.tools/zi/%F0%A9%89%B3)    29273
  * 依據：
    * 《可洪音义研究——以文字为中心》韩小荆.2009.巴蜀书社 p472，認爲是異體字關係。
* CB02517    `[(畾/且)*毛]`
  * 推薦：[㲲](https://zi.tools/zi/%E3%B2%B2)    3CB2
  * 依據：
	* 檢查高麗再雕原圖，與推薦字“㲲”一致。
    * 推薦字的字義與上下文相符
* CB13383    [黍-禾+唎]
  * 推薦：[𭊵](https://zi.tools/zi/%F0%AD%8A%B5)    2D2B5
  * 依據：
    * 查閱高麗初雕、再雕等，均爲“𭊵”，與組字式的差異在下面的“水”變成“小”
    * 頻伽藏爲“嚟”。
    * 這兩種變形都是異體字常見變形，建議依據高麗本。

**Comment by mahawu** [comment]
感謝提供這些缺字資訊！我們會 "見好就收"。 :)

**Comment by CallMeNP** [comment]
提出只是一小步，審覈檢驗要付出的勞動比提出整理要多。甚至提出還帶有個人的隨意性，審覈正是要按照統一標準抉擇。所以“見好就收”就是最好了。合十。
